name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup go env
        uses: actions/setup-go@master
        with:
          go-version: "1.21"
      - name: goreleaser with tag
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        id: extract-version
        run: |
          echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: bump homebrew-core formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: harbor
          formula-path: Formula/harbor.rb
          download-url: https://github.com/goharbor/harbor-cli/archive/${{ steps.extract-version.outputs.tag-name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
