name: Dagger Release Pipeline

on:
  push:
    tags:
      - "v*"
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  publish-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          cache: true

      - name: Run Dagger Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run ci/dagger.go release ${{ env.GITHUB_TOKEN }}
