name: Pull Request Pipeline

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - '*.md'
      - 'assets/**'

permissions:
  contents: write # This is required for actions/checkout
  packages: write # This is required for publishing the package

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dagger Version
        uses: sagikazarmark/dagger-version-action@v0.0.1

      - name: Run Linters
        uses: dagger/dagger-for-github@v6
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: lint

      - name: Run Tests
        uses: dagger/dagger-for-github@v6
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: test

      - name: Build Binary
        uses: dagger/dagger-for-github@v6
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: build-dev --platform linux/amd64

  push-snapshop-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dagger Version
        uses: sagikazarmark/dagger-version-action@v0.0.1

      - name: Push Release
        uses: dagger/dagger-for-github@v6
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: snapshot-release --github-token=${{ env.GITHUB_TOKEN }}
