name: Dagger Pull Request Pipeline

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - '*.md'
      - 'assets/**'

permissions:
  contents: write # This is required for actions/checkout
  packages: write # This is required for publishing the package

jobs:
  test-code:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dagger Version
        uses: sagikazarmark/dagger-version-action@v0.0.1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Test with the Go CLI
        run: go test -v ./...

      - name: Call Linting Function
        uses: dagger/dagger-for-github@v6
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: lint --source=.

      - name: Call Build Function
        uses: dagger/dagger-for-github@v6
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: build --source=.

      - name: Call Pull-Request Function
        uses: dagger/dagger-for-github@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: pull-request --source=. --github-token=${{ env.GITHUB_TOKEN }}
