name: Sign

on:
  push:
    branches: [main]

jobs:
  sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dagger Version
        uses: sagikazarmark/dagger-version-action@v0.0.1

      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE

      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Sign Image
        uses: dagger/dagger-for-github@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_ADDRESS: ${{ vars.REGISTRY_ADDRESS }}
          REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          IMAGE: "library/harbor-cli@sha256:9183ba01537f21c44d2aba0ca8ad500ffe6d80baea748f52b72d75be1dd19a84"
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: "sign --github-token=env:GITHUB_TOKEN \
          --actions-id-token-request-url='${{ ACTIONS_ID_TOKEN_REQUEST_URL }}' \
          --actions-id-token-request-token=env:ACTIONS_ID_TOKEN_REQUEST_TOKEN \
          --registry='${{ env.REGISTRY_ADDRESS }}' \
          --registry-username='${{ env.REGISTRY_USERNAME }}' \
          --registry-password=env:REGISTRY_PASSWORD \
          --image-name='${{ env.IMAGE }}'"
